apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cit-us-east-2
  namespace: argocd
spec:
  description: CIT environment in us-east-2
  sourceRepos:
    - https://github.com/ikigai-weichen-l/central-repo.git
    - https://github.com/ikigai-weichen-l/project-repo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*-cit-us-east-2'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
