apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: slot
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/ikigai-weichen-l/central-repo.git
    - https://github.com/ikigai-weichen-l/project-repo.git
  destinations:
    - namespace: slot
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
