apiVersion: apps/v1
kind: Deployment
metadata:
  name: slot-game
  namespace: slot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slot-game
  template:
    metadata:
      labels:
        app: slot-game
    spec:
      containers:
        - name: slot-game
          image: ghcr.io/ikigai-weichen-l/project-repo:f14a52dd55aa768bce204d4d04803f55256954a7
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: slot-game
  namespace: slot
spec:
  selector:
    app: slot-game
  ports:
    - port: 80
      targetPort: 8080
