apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-worker-app
  template:
    metadata:
      labels:
        app: my-worker-app
    spec:
      containers:
        - name: app
          image: mendhak/http-https-echo:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: my-app-config
            - secretRef:
                name: my-app-secret
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
