apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app-set
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/ikigai-weichen-l/central-repo.git
        revision: main
        files:
          - path: "apps/*/deployments/*/*/*.yaml"
  template:
    metadata:
      name: '{{ index .path.segments 1 }}-{{ lower (index .path.segments 3) }}-{{ index .path.segments 4 }}-{{ trimSuffix ".yaml" .path.filename }}'
      namespace: argocd
    spec:
      project: default
      sources:
        - repoURL: https://github.com/ikigai-weichen-l/central-repo.git
          targetRevision: main
          path: "apps/{{ index .path.segments 1 }}/base"
          directory:
            include: "{{ .path.filename }}"

        - repoURL: https://github.com/ikigai-weichen-l/project-repo.git
          targetRevision: main
          path: 'kustomize/overlays/{{ index .path.segments 3 }}/{{ index .path.segments 4 }}/{{ trimSuffix ".yaml" .path.filename }}'

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ index .path.segments 1 }}-{{ lower (index .path.segments 3) }}-{{ index .path.segments 4 }}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
