apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: demo-test-secret-store
spec:
  provider:
    fake:
      data:
        - key: DATABASE_URL
          value: postgresql://demo:demo@localhost:5432/demo
        - key: API_KEY
          value: local-test-api-key
