apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slot-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: slot
  source:
    repoURL: https://github.com/ikigai-weichen-l/central-repo.git
    targetRevision: main
    path: apps/slot/base
  destination:
    server: https://kubernetes.default.svc
    namespace: slot # deployment target
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
