apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-worker-app
  template:
    metadata:
      labels:
        app: my-worker-app
    spec:
      containers:
        - name: app
          image: ghcr.io/ikigai-weichen-l/project-repo:f14a52dd55aa768bce204d4d04803f55256954a7
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-app-shared-config
            - configMapRef:
                name: my-app-slot-worker-config
            - secretRef:
                name: my-app-shared-secret
            - secretRef:
                name: my-app-slot-worker-secret
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
