apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slot-app
  namespace: argocd
spec:
  project: slot
  sources:
    - repoURL: https://github.com/ikigai-weichen-l/central-repo.git
      targetRevision: main
      path: apps/slot/base
      kustomize: {}

    - repoURL: https://github.com/ikigai-weichen-l/project-repo.git
      targetRevision: main
      path: kustomize/overlays/slot/slot-app
      kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: slot # ← 部署到 slot namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
